CREATE TABLE `website_audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`userId` int NOT NULL,
	`url` varchar(512) NOT NULL,
	`status` enum('pending','scraping','analyzing','complete','failed') NOT NULL DEFAULT 'pending',
	`pageTitle` varchar(512),
	`metaDescription` text,
	`ogTags` json,
	`canonicalUrl` varchar(512),
	`language` varchar(16),
	`favicon` varchar(512),
	`hasRobotsTxt` boolean,
	`hasSitemapXml` boolean,
	`isHttps` boolean,
	`responseTimeMs` int,
	`securityHeaders` json,
	`seoIssues` json,
	`socialLinks` json,
	`detectedTech` json,
	`llmAnalysis` json,
	`executiveSummary` text,
	`errorMessage` text,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `website_audits_id` PRIMARY KEY(`id`)
);
